### ISSUE TITLE
error when running sampleExperience

### ISSUE THREAD

**Issue by salma-daoud** [nproellochs/ReinforcementLearning#7]
Hello,
when I run sampleExperience to get data,the following error occurs:

> data <- sampleExperience(N = 10, env = env, states = states_names, actions = actions)

```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0
```

[Open error](https://drive.google.com/file/d/1MtNQDtC8uVYap8DChmmRWvx1cWUlVqTT/view?usp=sharing)

any idea? thanks

**Comment by nproellochs** [comment]
Hi salma-daoud,

Could you kindly post a complete example? Otherwise, it is difficult to reproduce the error.

Best,
Nicolas

**Comment by b-rodrigues** [comment]
Hi @nproellochs , I thought I had a similar issue, but actually my `env` function returned NextSate (without a T) instead of NextS**t**ate.

I'll be leaving my original message below for posterity. It's a good example of rubber duck debugging, but instead of explaining to the rubber duck it was writing it down.
Perhaps there could be an error message if the next state is not called exactly NextState and reward Reward?

Cheers

*****************************************************************************************************
 
Hi @nproellochs I have a similar issue, here's some reproducible code:

```
library(ReinforcementLearning)

cake_process <- function(state, action){
    next_state <- state
    if(state == state("complete") && action == "eat") {
        next_state <- state("no_more")
    if(next_state == state("no_more") && state != state("no_more"))
    reward <- 10
    }
    else {
        reward <- 0
    }
    out <- list(NextSate = next_state, Reward = reward)
    return(out)
}

states <- c("complete", "no_more")
actions <- c("eat", "dont_eat")

sampleExperience(N = 10, 
                 env = cake_process,
                 states = states,
                 actions = actions)
```

Here's the error message:

```
Error in data.frame(State = sampleStates, Action = sampleActions, Reward = response$Reward,  : 
  arguments imply differing number of rows: 10, 0
```

So what I did was look into the code of sampleExperience. First I changed the data.frame function to a tibble::tibble() function:

```
sample_exp <- function (N, env, states, actions, actionSelection = "random", 
                        control = list(alpha = 0.1, gamma = 0.1, epsilon = 0.1), 
                        model = NULL, ...) 
{
    if (!(N > 0 && length(N) == 1 && is.numeric(N) && floor(N) == 
          N)) {
        stop("Argument 'N' should be an integer > 0.")
    }
    if (!is.function(env)) {
        stop("Argument 'env' describing the environment must be of type function.")
    }
    if (!is.character(states)) {
        stop("Arguments 'states' must be of type 'character'.")
    }
    if (!is.character(actions)) {
        stop("Arguments 'actions' must be of type 'character'.")
    }
    if (class(model) != "rl" && !is.null(model)) {
        stop("Argument 'model' must be empty or of type 'rl'.")
    }
    if (!is.list(control)) {
        stop("Argument 'control' must be of type 'list'.")
    }
    if (is.null(control$epsilon)) {
        stop("Missing or invalid control parameters.")
    }
    if (is.null(model)) {
        Q <- hash::hash()
    }
    else {
        Q <- model$Q_hash
    }
    for (i in unique(states)[!unique(states) %in% names(Q)]) {
        Q[[i]] <- hash::hash(unique(actions), rep(0, length(unique(actions))))
    }
    actionSelectionFunction <- ReinforcementLearning:::lookupActionSelection(actionSelection)
    sampleStates <- sample(states, N, replace = T)
    sampleActions <- sapply(sampleStates, function(x) actionSelectionFunction(Q, 
                                                                              x, control$epsilon))
    response <- lapply(1:length(sampleStates), function(x) env(sampleStates[x], 
                                                               sampleActions[x]))
    response <- data.table::rbindlist(lapply(response, data.frame))
    out <- tibble(State = sampleStates, Action = sampleActions, 
                      Reward = response$Reward, NextState = as.character(response$NextState), 
                      stringsAsFactors = F)
    return(out)
}

sampleExperience(N = 10, 
                 env = cake_process,
                 states = states,
                 actions = actions)
```

```
 Error: Tibble columns must have consistent lengths, only values of length one are recycled:
* Length 0: Column `NextState`
* Length 10: Columns `State`, `Action`, `Reward`
Run `rlang::last_error()` to see where the error occurred. 
```

Seems like the problem comes from the `NextState` column. So let me add a browser() function just before `out` is defined. I then copy paste the problematic code, and indeed, it doesn't work

https://i.imgur.com/TVbgjwI.png

However, looking into `reward$NextState` I do see a vector:

https://imgur.com/tfUA6Uc.png

I'm dumbfounded.

********************************************

Yep, in the last picture we can see it's reward$NextSate, missing the first **t**....

**Comment by nproellochs** [comment]
Dear Bruno,
Thanks for sharing your thoughts - much appreciated! I will definitely consider adding a corresponding warning message as part of the next package update.
Best,
Nicolas

**Comment by nproellochs** [comment]
Resolved. SampleExperience() now shows a warning message if the environment function does not return named items for "NextState" and "Return."
